
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'qaz123++'
  redis: 'qaz123++'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'zqnez5OWy8yGXDqZFDXatdy0n-xzJDD4'

  emailSecretHashPepper: 'Xr2EQGecBOac_Fbtja7wMaJ_eVcHYyxJ'
  jwtHmacSha512PrivateKey: 'cHv-Vg85utdvGGDDAwqYQacJ79kcV3Aw'
  jwtRefreshTokenHashPepper: 'KaMTR8VV9upOh_Q-ktj8tBUb9pVCN74X'
  # serverSideSessionKeyHashPepper: 'BPqEZv1m-aXP71OJECUC5MArxPcouLcF'

# test:
#   database: 'pvHt_A4DvbqS7cGAOnPXKJYXCthx8c_X'
#   redis: 'jgX9TZ0GKdSsIT7MxqOnQaTyPnAYoMmL'

#   emailSecretHashPepper: 'zLj1DHPzkFpdB6jD_MTGsmxD1MoC7sHG'
#   jwtHmacSha512PrivateKey: 'nxZgDU2Om6uCkWjHQTYs48l5WBjsaSKK'
#   jwtRefreshTokenHashPepper: '0vUdvlS-M82MeBRw_wMyLJyFGQD-T21V'
  # serverSideSessionKeyHashPepper: 'YDoC92Tg3P-x3K8Odbbh3MjVpvXvIwGp'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
# staging:
#   database: 'eRvos56ATLsUGuST7OuiqyQPMaUhtldO'
#   serviceSecret: '1nDLea4vBx6SgUgSHrMv33ciUuJRgkMQ'

#   emailSecretHashPepper: 'z5domAvpRUY2BhCp5-_ZCSGCvnbWqPXg'
#   jwtHmacSha512PrivateKey: 'ujNQ1sG7RAEsUuA8zHP3RMZ0NCjjVSbB'
#   jwtRefreshTokenHashPepper: 'AyEV7C6cMhSByJRql_8FJvPkIsWH2fnL'
  # serverSideSessionKeyHashPepper: 'JCULhovb5-k8iS8RsGkSo7iwc8h_aMAN'

# Passwords used in production mode.
production:
  database: 'qaz123++'
  serviceSecret: 'sCT9MNw6YK_9ER1aoO2Z7BYp29s2kP0q'

  emailSecretHashPepper: 'WLcLOsEehkO7N2tKzLORrjGDv_o1xPwn'
  jwtHmacSha512PrivateKey: 'WfED2dv75T5_8UNyCe3bzVlJ_xiOx5M0'
  jwtRefreshTokenHashPepper: 'CYrNzKPjJg-VlH9uB6wyA0itE9vJPd42'
  # serverSideSessionKeyHashPepper: 'qUBan7OoGrLFjLVRpLVAHSGDMZOF4d1e'